[package]
name = "corlib"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A various ideas library"
repository = "https://github.com/coruscateor/corlib"
homepage = "https://coruscateor.com/projects/corlib"
keywords = ["general", "purpose", "collections", "events", "non-option"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delegate = "0.*"
paste = "1.0.*"


